treewide: Fix error cause a function declaration is deprecated Fixed error on clang 16
kernel/xiaomi/sm6150/drivers/input/touchscreen/gt9896/goodix_ts_tools.c:543:26:
error: a function declaration without a prototype is deprecated in all
versions of C [-Werror,-Wstrict-prototypes]
int goodix_tools_register()

kernel/xiaomi/sm6150/drivers/input/touchscreen/gt9896/goodix_ts_tools.c:556:28:
error: a function declaration without a prototype is deprecated in all
versions of C [-Werror,-Wstrict-prototypes]
int goodix_tools_unregister()

kernel/xiaomi/sm6150/drivers/misc/wl2866d.c:81:34: error: a function
declaration without a prototype is deprecated in all versions of C
[-Werror,-Wstrict-prototypes]
int wl2866d_camera_power_down_all()

Signed-off-by: unsatifsed27
<unsatifsederror@gmail.com>